### ISSUE TITLE
NoMethodError: undefined method 'unescape_path' for Rack::Utils:Module

### ISSUE THREAD

**Issue by prashant-kiwi** [cyu/rack-cors#191]
I am getting NoMethodError for 'unescape_path' for Rack::Utils:Module.
When I deep dug then found that my project was running on version "1.0.3" but when i deploy the code today then 'rack-cors' gem updated to new version which is "1.0.4"

**Comment by Mikkie-Cutcopy** [comment]
same error

**Comment by denqxotl** [comment]
Use 1.0.3 version. I have the same error.
I believe that u need to have a new version of rack to use rack-cors 1.0.4
So, for old rails/rack versions just use rack-cors 1.0.3

**Comment by shawnwonolo** [comment]
I am seeing the same thing. I am on rack 1.6.11 if that helps.

**Comment by vlad-pisanov** [comment]
Problem is here: https://github.com/cyu/rack-cors/blob/e4d4fc362a4315808927011cbe5afcfe5486f17d/lib/rack/cors.rb#L155

`path = Rack::Utils.clean_path_info(Rack::Utils.unescape_path(path)) if path`

`Rack::Utils.unescape_path` doesn't exist in Rack 1.x, it requires Rack 2.x

**Comment by cyu** [comment]
I've pushed up version 1.0.6 (had a mishap with using `unescape_path` instead of `unescape` 😔).  Sorry about the inconvenience, but thank you so much creating this issue.

**Comment by cyu** [comment]
I've also yanked 1.0.4 so that it's no longer available.

**Comment by daande** [comment]
@cyu Thank you for pushing up 1.0.6!

**Comment by tasos31** [comment]
this also happens in 1.0.5 (rack >= 1.6.0) for me. after updating to 1.0.6 it seems to work fine

**Comment by vishalzambre** [comment]
Getting same error after upgrade to `rack - 1.6.12` from `rack -1.6.11`
`rack-cors (1.0.5)` From `rack-cors (1.0.2)`

**Comment by mbijon** [comment]
Github's @dependabot is currently suggesting a bump to 1.0.5, which has this issue.

@cyu could you please yank release 1.0.5 too?

**Comment by jpowell** [comment]
@cyu see above comments about `1.0.5` - causing the same issue... and @dependabot recommending this version.

**Comment by cyu** [comment]
@mbijon @jpowell this is a damned if you do, damned if you don't situation - I got my hand slapped for yanking 1.0.4.

Maybe I can convince @dependabot to *not* recommend 1.0.5?  Pretty please @dependabot?

**Comment by mbijon** [comment]
@cyu how about releasing a reversion/patch as 1.0.6?
